### ISSUE TITLE
Docs from querys

### ISSUE THREAD

**Issue by jllunell** [eddelplus/CornerCouch#28]
Hi,

is it possible to have the "save" function on the returning docs from the query function:

 $scope.gbookdb.query("app", "utc_only", { include_docs: true, descending: true, limit: 8 });

My goal is to update docs that i have from the query without having to get the doc again by the Id to save it to database. I don't know if I can do this in some way, but i couldn't find it.

Thank you.

**Comment by eddelplus** [comment]
Hi, that is what the getQueryDoc(idx) methods (line 175 ff.) does. If the query result contains the complete docs, it will take that data and simply turn it into an object with approriatele prototype, so the save method can be chained onto it.
